import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Box } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  const theme = useTheme();
  return (
    <div className={styles.container} style={{ backgroundColor: theme.palette.primary.surface }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Box component={'main'} className={styles.main} sx={{ border: "3px solid blue" }}>

      </Box>

      <Footer />
    </div>
  )
}

export default Home
