import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.css'

import { Box, Fab, Stack, Typography } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import { motion, Variants } from 'framer-motion';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { BubbleChartOutlined, WorkOutlineRounded } from '@mui/icons-material';

const Home: NextPage = () => {
  const theme = useTheme();

  const sentence = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        delay: 0.5,
        staggerChildren: 0.08,
      }
    }
  }
  const letter = {
    hidden: { opacity: 0, y: 50 },
    visible: { opacity: 1, y: 0 }
  }
  const greeting = "Hello";

  const works: Variants = {
    offscreen: {
      y: 300,
      opacity: 0,
    },
    onscreen: {
      y: 0,
      opacity: 1,
      transition: {
        type: "spring",
        bounce: 0.2,
        duration: 0.8,
        delay: 0.4
      }
    }
  }

  return (
    <Box className={styles.container} sx={{ backgroundColor: theme.palette.primary.surface }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Box component={'main'} className={styles.main} >
        {/* Landing section */}
        <motion.div id='landing-section' viewport={{ once: true }} style={{ width: "100%", maxWidth: "1500px", marginTop: "7.5vh" }}>
          <Stack direction="row" alignItems="center" justifyContent="space-evenly" >
            <Stack direction="column" spacing={2} maxWidth="40%">
              <motion.h2
                variants={sentence}
                initial="hidden"
                animate="visible"
                style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText }}
              >
                {
                  greeting.split("").map((char, index: number) => {
                    return (
                      <motion.span key={char + "-" + index} variants={letter}>
                        {char}
                      </motion.span>
                    )
                  })
                }
              </motion.h2>
              <motion.div
                initial={{ opacity: 0, scale: 1 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText }}
              >
                <Typography variant='h3'>
                  I'm
                  <span lang='en' style={{ color: "#4ca771" }}> Jacob</span>
                  <br />
                  a
                  <span lang='en' style={{ color: "#4ca771" }}> Student </span>
                  at Northeastern
                </Typography>
              </motion.div>
              <motion.p
                initial={{ opacity: 0, scale: 1 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText, paddingTop: "16px" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </motion.p>
            </Stack>
            <motion.div
              initial={{ opacity: 0, scale: 1 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
            >
              <Image quality={95} src={"/portrait.jpg"} alt="Portrait image" placeholder='blur' blurDataURL="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mO8WQ8AAjcBWtrfQHkAAAAASUVORK5CYII=" width={750} height={660} style={{ borderRadius: "32px" }} />
            </motion.div>
          </Stack>
        </motion.div>

        { /* Work section */}
        <motion.div
          id='work-section'
          initial="offscreen"
          whileInView="onscreen"
          viewport={{ once: true }}
          style={{ width: "100%", maxWidth: "1500px", marginTop: "30vh" }}
        >
          <motion.div variants={works}>
            <Stack direction="row" alignItems="center" justifyContent="space-evenly" >
              <Image quality={95} src={"/portrait.jpg"} alt="Portrait image" placeholder='blur' blurDataURL="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mO8WQ8AAjcBWtrfQHkAAAAASUVORK5CYII=" width={500} height={440} style={{ borderRadius: "32px" }} />
              <Stack direction="column" spacing={2} maxWidth="40%">
                <motion.div
                  initial={{ opacity: 0, scale: 1 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                  style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText }}
                >
                  <Typography variant='h4'>
                    This is test text for blurb about a project
                  </Typography>
                </motion.div>
                <motion.p
                  initial={{ opacity: 0, scale: 1 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                  style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText, paddingTop: "16px" }}
                >
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </motion.p>
                <motion.div>
                  <Fab variant='extended'
                    href='/work'
                    sx={{
                      backgroundColor: theme.palette.primary.primaryContainer,
                      color: theme.palette.primary.onPrimaryContainer,
                      maxWidth: "212px",
                      borderRadius: "16px",
                      marginTop: "16px"
                    }}
                  >
                    <WorkOutlineRounded sx={{ color: theme.palette.primary.onPrimaryContainer, mr: 1 }} />
                    Learn about my work
                  </Fab>
                </motion.div>
              </Stack>
            </Stack>
          </motion.div>

          { /* Testimonials section */}
          <motion.div
            id='testimonial-section'
            initial="offscreen"
            whileInView="onscreen"
            viewport={{ once: true }}
            style={{ width: "100%", maxWidth: "1500px", marginTop: "30vh" }}
          >
            <motion.div variants={works}>
              <Stack direction="row" alignItems="center" justifyContent="space-evenly" >

                <Stack direction="column" spacing={2} maxWidth="40%">
                  <motion.div
                    initial={{ opacity: 0, scale: 1 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                    style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText }}
                  >
                    <Typography variant='h4'>
                      This is test text for a testimonial
                    </Typography>
                  </motion.div>
                  <motion.p
                    initial={{ opacity: 0, scale: 1 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.67, delay: 0.33, ease: "easeInOut" }}
                    style={{ color: theme.palette.mode === "dark" ? theme.palette.secondary.contrastText : theme.palette.primary.contrastText, paddingTop: "16px" }}
                  >
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                  </motion.p>
                  <motion.div>
                    <Fab variant='extended'
                      href='/about'
                      sx={{
                        backgroundColor: theme.palette.primary.primaryContainer,
                        color: theme.palette.primary.onPrimaryContainer,
                        maxWidth: "212px",
                        borderRadius: "16px",
                        marginTop: "16px"
                      }}
                    >
                      <BubbleChartOutlined sx={{ color: theme.palette.primary.onPrimaryContainer, mr: 1 }} />
                      Learn more about me
                    </Fab>
                  </motion.div>
                </Stack>
                <Image quality={95} src={"/portrait.jpg"} alt="Portrait image" placeholder='blur' blurDataURL="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mO8WQ8AAjcBWtrfQHkAAAAASUVORK5CYII=" width={500} height={440} style={{ borderRadius: "32px" }} />
              </Stack>
            </motion.div>
          </motion.div>
        </motion.div>
      </Box>

      <Footer />
    </Box>
  )
}

export default Home
